# Site Info
title:              "Sekinat Yahya"
description:        "Academic Blog."

# Author Info
author_name:        "Sekinat Yahya"
author_gravatar:    e1787b206f52b9888a25efee56eee0d2 # Gravatar md5 hash
twitter_username:   _sakinah__

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
markdown:           kramdown
kramdown:
    input:          GFM
    math_engine:    mathjax
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt", "pages" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"

links:
  - name:         fa fa-graduation-cap
    alias:        publ
    info:         Publications
    url:          /publ
  - name:         fa fa-code
    alias:        code
    info:         Resources
    url:          /code
  - name:         fa fa-tasks
    alias:        work
    info:         Activities
    url:          /work
  - name:         fa fa-user-circle
    alias:        about
    info:         README
    url:          /about
  - name:         fab fa-twitter
    url:          https://twitter.com/_sekinah__
    info:         Twitter
  - name:         fab fa-github
    url:          https://github.com/sekinat95
    info:         GitHub

  - name:          fa fa-sharp fa-regular fa-user-graduate
    url:          https://scholar.google.com/citations?user=6Y7OKF8AAAAJ&hl=fr
    info:         Google Scholar

  #- name:         fa fa-envelope
  #  url:          https://sakinah.substack.com/
  #  info:         Substack

